Add default templates and fix porting issues
schana/recommendation-api pull request #1
Opened 2017-05-12 12:57 UTC by schana

https://phabricator.wikimedia.org/T164282#3256788

2017-05-12 13:36 UTC, schana commented
@d00rman Would you mind reviewing this? Afterwords I'll send the requests to get the Gerrit repos setup.

2017-05-16 00:22 UTC, d00rman requested changes
Looking good! A couple of minor issues and we should be good to go.

2017-05-16 00:22 UTC, d00rman commented on config.dev.yaml
> +        headers:
Should also probably add `content-type: application/json` to the list of headers

2017-05-16 00:22 UTC, d00rman commented on lib/translation.js
> +            headers: {
Idem, `content-type` should be here as well.

2017-05-16 00:22 UTC, d00rman commented on routes/translation.js
> +    if (Object.hasOwnProperty.call(req.query || {}, 'count')) {
Easier: `if (req.query && req.query.count)`

2017-05-16 00:22 UTC, d00rman commented on routes/translation.js
> +        if (isNaN(count)) {
You should also check that the number is between 1 and a reasonable max value

2017-05-16 12:04 UTC, schana commented
Adding a content-type header to the WDQS requests results in a 405 response

2017-05-16 14:05 UTC, d00rman commented
> Adding a content-type header to the WDQS requests results in a 405 response

This is weird. That should probably be reported to Discovery.

2017-05-16 14:08 UTC, merged